version: '3'
services:
    web:
        ports:
            - 80:80
            - 443:443
    mysqlhost:
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysqlhost
            - PMA_PORT=3306
        ports:
            - 8080:80